# Generated by Django 3.2.12 on 2024-03-10 19:37

import DesignGenerator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to=DesignGenerator.models.PathAndRename('user')),
        ),
    ]
