# Generated by Django 3.2.12 on 2024-03-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignGenerator', '0002_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
