# Generated by Django 3.2.12 on 2024-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignGenerator', '0003_alter_portfolio_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
        ),
    ]
