# Generated by Django 3.2.12 on 2024-03-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DesignGenerator', '0004_galleryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
