# Generated by Django 5.0.3 on 2024-03-20 07:09

import DesignGenerator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignGenerator', '0009_remove_portfolio_likes_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='remove_bg',
            field=models.ImageField(blank=True, null=True, upload_to=DesignGenerator.models.PathAndRename('user')),
        ),
    ]
