# Generated by Django 5.0.3 on 2024-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DesignGenerator', '0010_portfolio_remove_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
