# Generated by Django 5.0.3 on 2024-03-17 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_auto_20240226_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='payment_made',
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_details', models.TextField(blank=True, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('id_proof', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_made', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
