# Generated by Django 5.0.3 on 2024-03-22 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_remove_user_bank_details_remove_user_id_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_body_image',
            field=models.ImageField(blank=True, null=True, upload_to='full_body_images/'),
        ),
        migrations.CreateModel(
            name='VirtuallyTried',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='virtually_tried_images/')),
                ('cloth_image', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
