# Generated by Django 4.2.4 on 2024-02-25 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_cart_sqp_cart_sqp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
