# Generated by Django 4.2.4 on 2024-02-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_sqp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
