# Generated by Django 3.2.12 on 2024-02-26 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DesignGenerator', '0001_initial'),
        ('Products', '0004_alter_sqp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DesignGenerator.portfolio'),
        ),
    ]
