# Generated by Django 3.2.12 on 2024-03-04 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_cart_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqp',
            name='quality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sqp',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
