# Generated by Django 3.2.12 on 2024-03-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20240304_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sqp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
