# Generated by Django 5.0.3 on 2024-03-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_alter_sqp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
